### ISSUE TITLE
Bumping xcb version

### ISSUE THREAD

**Issue by meh** [rtbo/xkbcommon-rs#1]
Any chance of bumping the version of the `xcb` dependency and publishing a new version so it avoids building two different versions of `xcb`?

I tested with a bumped version locally and it works, in theory it shouldn't be an issue to use two different versions because the API boundaries are just integers, but it's annoying to need two separate versions and inflates binary size.

**Comment by meh** [comment]
Actually it is a blocking issue, it won't recognize the `xcb::Connection`.

**Comment by rtbo** [comment]
bumped [v0.2.1](https://github.com/rtbo/xkbcommon-rs/releases/tag/v0.2.1) that depends on `xcb-0.7.*`.
