### ISSUE TITLE
Constructors possibly misplaced

### ISSUE THREAD

**Issue by fooishbar** [rtbo/xkbcommon-rs#2]
I don't actually know anything about Rust, so I could be completely wrong here. But, that's never stopped anyone on the internet from offering their opinion, so ...

Aren't the constructors for keymaps and states misplaced? I would expect that, rather than xkb.Keymap.new_from_names(ctx, ...), I'd be calling ctx.keymap_new_from_names(...). Ditto for the state constructor, which seems like it could live on the keymap object rather than taking it as an argument.

Thanks a lot for doing the bindings!

**Comment by rtbo** [comment]
> Aren't the constructors for keymaps and states misplaced?
Actually no.
`Type::new()` is a very common idiom in Rust to build objects.

**Comment by fooishbar** [comment]
Great! That was easy; sorry for the noise.
